INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Hydrogen', '2', '23.59', '13', 'img1.jpg', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Helium', '2', '57.65', '10', 'img2.jpg', 'Sed egestas libero ut ipsum.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Lithium', '2', '45.22', '1', 'img3.jpg', 'Proin tincidunt iaculis enim.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Beryllium', '3', '98.52', '2', 'img4.jpg', 'Nunc ultricies orci at quam.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Boron', '0', '23.59', '13', 'img5.jpg', 'Curabitur aliquet augue nec orci.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Carbon', '0', '57.65', '20', 'img6.jpg', 'Nulla vehicula pharetra tellus.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Nitrogen', '3', '45.22', '6', 'img7.jpg', 'Aenean nec erat vel ipsum rutrum ornare.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Oxygen', '2', '98.52', '10', 'img8.jpg', 'Vestibulum consectetuer risus quis lectus.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Fluorine', '0', '23.59', '16', 'img9.jpg', 'Nulla adipiscing semper arcu.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Neon', '1', '57.65', '13', 'img10.jpg', 'Cras cursus consectetuer pede.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Sodium', '2', '45.22', '11', 'img11.jpg', 'Sed tempus auctor nisi.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Magnesium', '1', '98.52', '17', 'img12.jpg', 'Aenean non libero eget elit scelerisque auctor.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Aluminum', '1', '23.59', '7', 'img13.jpg', 'Nullam condimentum malesuada orci.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Silicon', '1', '57.65', '2', 'img14.jpg', 'Mauris ac lacus vel magna elementum dapibus.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Phosphorus', '1', '45.22', '10', 'img15.jpg', 'Vivamus fringilla augue elementum est.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Sulfur', '0', '98.52', '11', 'img16.jpg', 'Vestibulum egestas blandit neque.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Chlorine', '3', '23.59', '10', 'img17.jpg', 'Phasellus rhoncus blandit pede.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Argon', '3', '57.65', '7', 'img18.jpg', 'Nam dapibus turpis vel risus.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Potassium', '1', '45.22', '5', 'img19.jpg', 'Sed sodales sagittis metus.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Calcium', '0', '98.52', '5', 'img20.jpg', 'Aenean sit amet mi ac felis suscipit vehicula.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Scandium', '0', '23.59', '14', 'img21.jpg', 'Nullam porttitor eleifend libero.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Titanium', '3', '57.65', '3', 'img22.jpg', 'Mauris in elit ac quam ultricies feugiat.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Vanadium', '0', '45.22', '6', 'img23.jpg', 'Vestibulum posuere posuere lectus.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Chromium', '0', '98.52', '2', 'img24.jpg', 'Sed laoreet magna id sem.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Manganese', '0', '23.59', '18', 'img25.jpg', 'Quisque laoreet sagittis est.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Iron', '2', '57.65', '20', 'img26.jpg', 'Curabitur vulputate nulla et orci.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Cobalt', '2', '45.22', '11', 'img27.jpg', 'In vestibulum arcu vulputate felis.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Nickel', '2', '98.52', '3', 'img28.jpg', 'Quisque vel quam sit amet orci tincidunt ullamcorper.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Copper', '2', '23.59', '11', 'img29.jpg', 'Sed egestas tortor id augue.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Zinc', '2', '57.65', '18', 'img30.jpg', 'Donec ultrices quam quis diam.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Gallium', '0', '45.22', '10', 'img31.jpg', 'Fusce volutpat scelerisque tortor.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Germanium', '2', '98.52', '3', 'img32.jpg', 'Proin luctus ligula sed dui.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Arsenic', '3', '23.59', '11', 'img33.jpg', 'Donec mollis tempor odio.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Selenium', '3', '57.65', '9', 'img34.jpg', 'Maecenas pretium porta pede.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Bromine', '2', '45.22', '5', 'img35.jpg', 'Nunc condimentum fermentum est.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Krypton', '2', '98.52', '16', 'img36.jpg', 'Etiam luctus tempus nulla.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Rubidium', '0', '23.59', '14', 'img37.jpg', 'Donec pretium cursus ante.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Strontium', '3', '57.65', '1', 'img38.jpg', 'Duis accumsan arcu ac eros.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Yttrium', '0', '45.22', '5', 'img39.jpg', 'Phasellus rutrum quam eu diam.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Zirconium', '3', '98.52', '12', 'img40.jpg', 'Proin vel dui ut felis sollicitudin lobortis.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Niobium', '0', '23.59', '15', 'img41.jpg', 'Ut ac turpis ac eros ultricies sodales.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Molybdenum', '3', '57.65', '17', 'img42.jpg', 'Vivamus porttitor mattis dolor.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Technetium', '1', '45.22', '5', 'img43.jpg', 'Ut sodales tellus eu erat.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Ruthenium', '1', '98.52', '13', 'img44.jpg', 'In viverra lacinia tellus.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Rhodium', '0', '23.59', '18', 'img45.jpg', 'Sed sed mauris sed magna porta cursus.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Palladium', '2', '57.65', '2', 'img46.jpg', 'Nam convallis diam id erat sodales aliquet.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Silver', '2', '45.22', '14', 'img47.jpg', 'Donec eget lorem at risus placerat vehicula.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Cadmium', '3', '98.52', '2', 'img48.jpg', 'Nam viverra scelerisque dolor.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Indium', '0', '23.59', '12', 'img49.jpg', 'In eu nisi eget eros euismod ornare.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Tin', '1', '57.65', '13', 'img50.jpg', 'Aenean vehicula dolor ut felis.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Antimony', '1', '45.22', '15', 'img51.jpg', 'Nam et libero vel ipsum laoreet varius.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Tellurium', '0', '98.52', '16', 'img52.jpg', 'Nunc tristique pede eu lacus bibendum venenatis.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Iodine', '3', '23.59', '7', 'img53.jpg', 'In sed arcu ut leo euismod gravida.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Xenon', '2', '57.65', '17', 'img54.jpg', 'Pellentesque laoreet adipiscing ante.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Cesium', '0', '45.22', '20', 'img55.jpg', 'Ut fringilla porttitor orci.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Barium', '1', '98.52', '10', 'img56.jpg', 'Cras et nisl sed est luctus lobortis.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Lanthanum', '2', '23.59', '13', 'img57.jpg', 'Donec ac lorem nec turpis dapibus aliquam.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Cerium', '0', '57.65', '13', 'img58.jpg', 'Nunc rutrum malesuada velit.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Praseodymium', '0', '45.22', '3', 'img59.jpg', 'Aenean quis dui porta tellus rutrum ullamcorper.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Neodymium', '0', '98.52', '12', 'img60.jpg', 'Etiam consequat risus eget lorem.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Promethium', '2', '23.59', '1', 'img61.jpg', 'Pellentesque aliquet felis quis pede.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Samarium', '2', '57.65', '17', 'img62.jpg', 'Nullam convallis ligula elementum velit.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Europium', '3', '45.22', '11', 'img63.jpg', 'Aenean vel nunc sed lorem varius eleifend.');
INSERT INTO products (name, category_id, price, qty, image_url, description) VALUES ('Gadolinium', '3', '98.52', '9', 'img64.jpg', 'Mauris in pede sed justo porttitor porttitor.');
